/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int add(int a,int b)
{
	return a+b;
}

__attribute__((naked)) void change_to_PSP(void)
{
	__asm volatile(".equ SRAM_END ,(0x2000000 + (128*1024))");//start of stack = end of SRAM
	__asm volatile(".equ PSP_START,(SRAM_END - 512)");//Stack is divided into 2 parts,PSP starts from middle
	__asm volatile("LDR R0 ,=PSP_START");//using R0 register to load PSP address
	__asm volatile("MSR PSP,R0");//PSP is loaded with PSP start address
	__asm volatile("MOV R0,#0x02");//  bit num 1 of control register must be 1 for using psp mode
	__asm volatile("MSR CONTROL,R0");//control register bit[1] is made high to use PSP
	__asm volatile("BX LR"); //Lr contains the return address, BX will load PC with LR value
}

void generate_exception(void)
{
__asm volatile("SVC 	#0x02");//svc exception generation
}

int main(void)
{
	change_to_PSP();//changing the SP to PSP

	int sum = add(7,9);

	//printf("%d\n",sum);

	generate_exception();//for changing the PSP to MSP.since it cannot be done directly

    /* Loop forever */
	//for(;;);
}

void SVC_Handler(void)
{
	printf("IN SVC HANDLER\n");
}
