/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//keyword for using assembly code in C program, volatile is make code non optimized.
	//=# is used for loading immediate values in address
	//loading R1 value in R0
	//loading R2 value in R1
	//adding values in R0 and R1 and saving it in R0
	//storing R0 registers value in R2

#if 0
	__asm volatile("LDR R1,=#0x20001000");
	__asm volatile("LDR R2,=#0x20001004");
	__asm volatile("LDR R0,[R1]");
	__asm volatile("LDR R1,[R2]");
	__asm volatile("ADD R0,R0,R1");
	__asm volatile("STR R0,[R2]");



	int val = 2;
__asm volatile("MOV R0,%0" : : "r"(val));//moving contents of c variable val to R0 register

int controlreg;

__asm volatile("MRS %0,CONTROL":"=r"(controlreg));//storing contents of control register to C variable

int a1=5 ,a2;
__asm volatile("MOV %0,%1":"=r"(a2):"r"(a1));//moving contents of one c variable to another like a2=a1
printf("%d\n",a2);

int p,*p1 = (int*)0x20001000;
__asm volatile("LDR %0,[%1]":"=r"(p):"r"(p1));//moving contents of p1 pointer into c variable
printf("%d\n",p);
#endif

  __asm volatile("MRS R0,CONTROL");//moving contents of control register to R0
  __asm volatile("ORR R0,R0,#0x01");//to set the first bit of control register,0x01 is OR with R0 contents(control register content)
  __asm volatile("MSR CONTROL,R0");//moving the contents of R0 to control register.

}
